# Generated by Django 3.2 on 2021-04-22 09:29

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default=user.models.generate_name, max_length=24),
        ),
    ]
