# Generated by Django 3.2 on 2021-04-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
    ]
