# Generated by Django 3.2 on 2021-04-26 08:55

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_score'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
