# Generated by Django 3.2 on 2021-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='facebooklink',
            field=models.CharField(default='', max_length=100),
        ),
    ]
