# Generated by Django 3.1.7 on 2021-04-10 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('profil', '0004_auto_20210410_1901'), ('profil', '0005_anonymousprofil'), ('profil', '0006_auto_20210410_2000'), ('profil', '0007_auto_20210410_2009'), ('profil', '0008_auto_20210410_2011'), ('profil', '0009_auto_20210410_2033'), ('profil', '0010_auto_20210410_2036')]

    dependencies = [
        ('profil', '0003_auto_20210410_1432_squashed_0004_remove_profil_facebooklink'),
        ('quiz', '0005_auto_20210410_1901'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.AddField(
            model_name='profil',
            name='created_at',
            field=models.DateTimeField(default=None, help_text='La date de création du profil.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfilInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', max_length=200)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='profil.profil')),
            ],
        ),
    ]
