# Generated by Django 3.1.7 on 2021-04-12 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profil', '0003_auto_20210410_1432_squashed_0004_remove_profil_facebooklink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='description',
        ),
        migrations.AddField(
            model_name='profil',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='La date de création du profil.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfilInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='profil.profil')),
            ],
        ),
    ]
