# Generated by Django 3.1.7 on 2021-04-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0005_auto_20210405_1826_squashed_0007_auto_20210405_1904'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='dataset_id',
        ),
        migrations.AddField(
            model_name='quiz',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='dataset.proxydataset'),
        ),
    ]
