# Generated by Django 3.1.7 on 2021-04-09 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('quiz', '0004_auto_20210409_1113'), ('quiz', '0005_auto_20210409_1116'), ('quiz', '0006_auto_20210409_1116'), ('quiz', '0007_auto_20210409_1116'), ('quiz', '0008_auto_20210409_1117'), ('quiz', '0009_auto_20210409_1117')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20210408_1633'),
        ('dataset', '0005_auto_20210405_1826_squashed_0007_auto_20210405_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(help_text="L'auteur du quiz.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(help_text='La date de création du quiz.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='dataset',
            field=models.ForeignKey(help_text='Le dataset source.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='dataset.proxydataset'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='', help_text='Le titre du quiz.', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='good_answers_count',
            field=models.IntegerField(default=0, help_text='Le nombre de question bien répondue.'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='quiz',
            field=models.ForeignKey(help_text='Le quiz en question.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='taken_at',
            field=models.DateTimeField(help_text='La date de soumission.'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='user',
            field=models.ForeignKey(help_text="L'utilisateur qui a fait la soumission.", on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='choices',
            field=models.JSONField(default=list, help_text="Les réponses que l'utilisateur a cochées."),
        ),
    ]
