# Generated by Django 3.1.7 on 2021-04-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_auto_20210410_1901'),
        ('quiz', '0004_auto_20210409_1113_squashed_0009_auto_20210409_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsubmission',
            name='good_answers_count',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='user',
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='profil',
            field=models.ForeignKey(help_text='Le profil utilisateur qui a fait la soumission.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_taken', to='profil.profil'),
        ),
    ]
