# Generated by Django 3.2 on 2021-04-14 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20210409_1113_squashed_0009_auto_20210409_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsubmission',
            name='good_answers_count',
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='user',
            field=models.ForeignKey(help_text="L'utilisateur qui a fait la soumission.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
